version: "2"

services:
  app:
    image: ghalibbajwa/slogr-controller-laravel:latest
    ports:
      - "8443:443"
    depends_on:
      - db
      - rabbitmq
    env_file:
      - .env

  frontend:
     image: ghalibbajwa/slogr-frontend:latest
     ports:
       - "80:80"
       - "443:443"
     env_file:
       - .env

  db:
    image: postgres
    command: postgres -c 'max_connections=300'
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

  migrate:
    image: ghalibbajwa/slogr-controller-laravel:latest
    depends_on:
      - db
      - app
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=laravel
      - DB_USERNAME=postgres
      - DB_PASSWORD=root
    command: sh -c 'php artisan migrate ; php artisan db:seed --class=ProfilesTableSeeder; php artisan db:seed --class=PermissionSeeder   ; php artisan view:clear; php artisan passport:install ; php artisa>

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: slogr123

volumes:
  db_data:
