version: "2"

services:
  app:
    image: 95ead854fc71
    ports:
      - "8080:80"
    depends_on:
      - db
    env_file:
      - .env
    
  db:
    image: postgres
    command: postgres -c 'max_connections=300'
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

  migrate:
    image: f4b8953c497d
    depends_on:
      - db
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=slogr
      - DB_USERNAME=slogr
      - DB_PASSWORD=slogr123
    command: sh -c 'php artisan migrate ; php artisan db:seed --class=ProfilesTableSeeder; php artisan db:seed --class=PermissionSeeder   ; php artisan view:clear; php artisan passport:install ; php artisan import:csv'

volumes:
  db_data:


